### ISSUE TITLE
When a downloadable product is added via "add product" action - the downloadable file is not added anywhere.

### ISSUE THREAD

**Issue by grig-23** [Prospress/automatewoo-subscriptions#40]
## Summary:

When a downloadable product is added via "add product" action - the downloadable file is not added under "downloads" or under "subscriptions >> Subscription X >> Downloads"

## Reported in: 

2741619-zen

## Steps to reproduce:

1. Create an AW workflow. I used "Subscription created" trigger and "add product" action. Under the action, select a product which is downloadable and has downloadable files attached to it.
2. Purchase a subscription product to trigger the above workflow.
3. Downloadable file attached to the simple product is not added anywhere in my-account.

![Screenshot](https://d.pr/i/AYrFns+)
Screenshot direct link: https://d.pr/i/AYrFns

The downloadable file will only be added to the "downloads" and "subscriptions >> Subscription X >> Downloads" after a renewal, not sure whether that is the expected behaviour.

**Comment by jessLundie** [comment]
> The downloadable file will only be added to the "downloads" and "subscriptions >> Subscription X >> Downloads" after a renewal, not sure whether that is the expected behaviour.

This is expected behavior, so it's a bit tricky. We've handled this on the order side by adding an order action _Trigger Order Action > Generate Download Permissions_. 

However, we don't have the equivalent action for a subscription. I added that to the Ideas Board here: https://ideas.automatewoo.com/automatewoo/p/add-action-trigger-subscription-action-generate-download-permissions

**Comment by danbitzer** [comment]
Also reported: 3186577-zen
